// <auto-generated />
using System;
using GunShopBackPart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GunShopBackPart.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260412160719_eedroducts")]
    partial class eedroducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GunShopBackPart.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GunShopBackPart.Models.BaseProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("BaseProducts", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GunShopBackPart.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaponPermit")
                        .HasColumnType("int");

                    b.Property<string>("gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GunShopBackPart.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSold")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Storage");
                });

            modelBuilder.Entity("GunShopBackPart.Models.ProductPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("GunPurchases");
                });

            modelBuilder.Entity("GunShopBackPart.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("GunShopBackPart.Models.Accessorie", b =>
                {
                    b.HasBaseType("GunShopBackPart.Models.BaseProduct");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.ToTable("Accessories", (string)null);
                });

            modelBuilder.Entity("GunShopBackPart.Models.Ammo", b =>
                {
                    b.HasBaseType("GunShopBackPart.Models.BaseProduct");

                    b.Property<int>("AmountInBox")
                        .HasColumnType("int");

                    b.Property<int>("Caliber")
                        .HasColumnType("int");

                    b.ToTable("Ammos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Description = "50 rounds",
                            Name = "9mm Ammo Box",
                            Price = 20m,
                            SupplierId = 1,
                            AmountInBox = 50,
                            Caliber = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "50 rounds",
                            Name = ".45 ACP Ammo",
                            Price = 25m,
                            SupplierId = 2,
                            AmountInBox = 50,
                            Caliber = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "30 rounds",
                            Name = "5.56 Ammo",
                            Price = 18m,
                            SupplierId = 3,
                            AmountInBox = 30,
                            Caliber = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "30 rounds",
                            Name = "7.62 Ammo",
                            Price = 22m,
                            SupplierId = 4,
                            AmountInBox = 30,
                            Caliber = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "25 shells",
                            Name = "12 Gauge Shells",
                            Price = 15m,
                            SupplierId = 5,
                            AmountInBox = 25,
                            Caliber = 4
                        });
                });

            modelBuilder.Entity("GunShopBackPart.Models.Gun", b =>
                {
                    b.HasBaseType("GunShopBackPart.Models.BaseProduct");

                    b.Property<int>("Caliber")
                        .HasColumnType("int");

                    b.Property<int>("GunType")
                        .HasColumnType("int");

                    b.ToTable("Guns", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "9mm pistol",
                            Name = "Glock 17",
                            Price = 500m,
                            SupplierId = 1,
                            Caliber = 0,
                            GunType = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = ".45 ACP pistol",
                            Name = "Colt 1911",
                            Price = 700m,
                            SupplierId = 2,
                            Caliber = 1,
                            GunType = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "5.56 rifle",
                            Name = "AR-15",
                            Price = 1200m,
                            SupplierId = 3,
                            Caliber = 2,
                            GunType = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "7.62 rifle",
                            Name = "AK-47",
                            Price = 1100m,
                            SupplierId = 4,
                            Caliber = 3,
                            GunType = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "12 gauge shotgun",
                            Name = "Remington 870",
                            Price = 400m,
                            SupplierId = 5,
                            Caliber = 4,
                            GunType = 2
                        });
                });

            modelBuilder.Entity("GunShopBackPart.Models.BaseProduct", b =>
                {
                    b.HasOne("GunShopBackPart.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GunShopBackPart.Models.InventoryItem", b =>
                {
                    b.HasOne("GunShopBackPart.Models.BaseProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GunShopBackPart.Models.ProductPurchase", b =>
                {
                    b.HasOne("GunShopBackPart.Models.Customer", "Customer")
                        .WithMany("GunPurchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GunShopBackPart.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("GunShopBackPart.Models.Accessorie", b =>
                {
                    b.HasOne("GunShopBackPart.Models.BaseProduct", null)
                        .WithOne()
                        .HasForeignKey("GunShopBackPart.Models.Accessorie", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GunShopBackPart.Models.Ammo", b =>
                {
                    b.HasOne("GunShopBackPart.Models.BaseProduct", null)
                        .WithOne()
                        .HasForeignKey("GunShopBackPart.Models.Ammo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GunShopBackPart.Models.Gun", b =>
                {
                    b.HasOne("GunShopBackPart.Models.BaseProduct", null)
                        .WithOne()
                        .HasForeignKey("GunShopBackPart.Models.Gun", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GunShopBackPart.Models.Customer", b =>
                {
                    b.Navigation("GunPurchases");
                });

            modelBuilder.Entity("GunShopBackPart.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
